repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: \.ipynb$
      - id: end-of-file-fixer
        exclude: \.ipynb$
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
        args: [--maxkb=5000]
      - id: detect-private-key
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
