# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 Rayk Kretzschmar
"""Fallow Finn -- tier 0 of the Kaggriculture reference ladder.

Never plants anything. The reward floor.

STRATEGY
Returns PASS on every one of the 720 turns and issues no market orders, so the farm ends the season exactly as it started.

WHAT THIS TIER TEACHES
Fixes the bottom of the scale. Any agent that cannot beat Finn is losing money somewhere -- usually by buying seeds or livestock it then fails to water or feed.

Measured end-of-season bank: about 3,000 coins against the built-in
`starter` baseline over a 720-turn season.

This file is self-contained. Rename it to `main.py` and it is a valid
competition submission; or import it and call `agent(obs)` directly.

Part of the Kaggriculture Reference Agents dataset:
https://www.kaggle.com/datasets/raykkretzschmar/kaggriculture-reference-agents
Generated by scripts/build_reference_ladder.py -- edit the policy there, not here.
"""

# The only thing that differs between the six ladder agents. Every tier runs the
# identical scheduler below, so any difference in results comes from these
# numbers alone -- which is what makes the ladder useful for learning.
POLICY = {}


# ---------------------------------------------------------------------------
# Shared action scheduler -- byte-identical in all six ladder agents.
# ---------------------------------------------------------------------------

# --- Engine constants (mirrored from kaggle_environments/envs/kaggriculture) ---

BOARD = 10
HALF = BOARD // 2
TURNS_PER_DAY = 24
SHED_CAP = 100

# Inner-corner tiles around the shed, in the engine's NWSE order. Only the ones
# inside an unlocked quadrant can actually service PICKUP / DROP.
SHED_TILES = [(HALF - 1, HALF - 1), (HALF, HALF - 1), (HALF - 1, HALF), (HALF, HALF)]

CROPS = {
    "WHEAT": {"seed": 10, "first": 2, "max_day": 4, "interval": 0, "cap": 6, "ongoing": False},
    "CARROT": {"seed": 20, "first": 2, "max_day": 3, "interval": 0, "cap": 4, "ongoing": False},
    "TOMATO": {"seed": 50, "first": 8, "max_day": 8, "interval": 1, "cap": 4, "ongoing": True},
    "STRAWBERRY": {
        "seed": 100,
        "first": 10,
        "max_day": 10,
        "interval": 2,
        "cap": 4,
        "ongoing": True,
    },
    "MELON": {"seed": 80, "first": 10, "max_day": 12, "interval": 0, "cap": 6, "ongoing": False},
}

ANIMALS = {
    "GOOSE": {
        "cost": 300,
        "structure": "COOP",
        "first": 4,
        "interval": 1,
        "cap": 4,
        "product": "EGG",
    },
    "COW": {
        "cost": 400,
        "structure": "PASTURE",
        "first": 8,
        "interval": 2,
        "cap": 6,
        "product": "MILK",
    },
    "SHEEP": {
        "cost": 500,
        "structure": "PASTURE",
        "first": 6,
        "interval": 3,
        "cap": 6,
        "product": "WOOL",
    },
}

PRODUCTS = ["WHEAT", "CARROT", "TOMATO", "STRAWBERRY", "MELON", "EGG", "MILK", "WOOL", "FERTILIZER"]

LAND_PRICES = [1000, 2000, 4000]

MOVE_OP = {(0, -1): "NORTH", (0, 1): "SOUTH", (1, 0): "EAST", (-1, 0): "WEST"}
_ROUTE_MEMORY = {}


# --- Small geometry helpers ---


def _quadrant(x, y):
    return ("N" if y < HALF else "S") + ("W" if x < HALF else "E")


def _dist(a, b):
    return abs(a[0] - b[0]) + abs(a[1] - b[1])


def _step_toward(pos, target):
    """One deterministic Manhattan step. Horizontal first, then vertical."""
    px, py = pos
    tx, ty = target
    if px != tx:
        return [MOVE_OP[(1, 0)] if tx > px else MOVE_OP[(-1, 0)]]
    if py != ty:
        return [MOVE_OP[(0, 1)] if ty > py else MOVE_OP[(0, -1)]]
    return ["PASS"]


def _shed_tile(tiles):
    """The first shed-access tile that is not LOCKED. (4,4) is always unlocked."""
    for x, y in SHED_TILES:
        if tiles[y][x] != "LOCKED":
            return (x, y)
    return SHED_TILES[0]


def _open_tiles(tiles):
    """Unlocked, empty tiles, nearest the shed first.

    Ordering matters more than it looks: every unit respawns at the shed each
    morning, so tiles far from it cost extra walking turns on every watering and
    feeding round. Clustering the farm inward is free throughput.
    """
    sx, sy = _shed_tile(tiles)
    out = []
    for y in range(BOARD):
        for x in range(BOARD):
            if tiles[y][x] is None:
                out.append((x, y))
    out.sort(key=lambda p: (abs(p[0] - sx) + abs(p[1] - sy), p[1], p[0]))
    return out


# --- Crop / animal reasoning ---


def _attainable_yield(crop, planted_day, day):
    """Units a one-time crop will hold if watered every remaining bonus day."""
    info = CROPS[crop]
    window_start = (info["max_day"] + 1) // 2
    days = max(0, min(info["max_day"], day) - window_start + 1)
    return min(info["cap"], 1 + days)


def _ready_to_harvest(tile, day, policy):
    """Should this plant be harvested now?"""
    crop = tile["crop"]
    info = CROPS[crop]
    age = day - tile["planted_day"]
    if age < info["first"]:
        return False
    if tile.get("yield_units", 0) <= 0:
        return False
    if info["ongoing"]:
        return True
    if policy.get("harvest_asap"):
        # Deliberately impatient: takes the first legal harvest and throws away
        # the rest of the watering bonus window.
        return True
    # Wait for the bonus window to finish, but never past the decay step.
    if age >= info["max_day"]:
        return True
    return tile["yield_units"] >= min(
        info["cap"], _attainable_yield(crop, tile["planted_day"], info["max_day"])
    )


def _build_plans(policy, day):
    """Structure plans that are active on this day."""
    return [
        p for p in policy.get("build", []) if p.get("from_day", 0) <= day <= p.get("until_day", 99)
    ]


def _season_phase(policy, obs):
    """Which of the three end-of-season gates are still open.

    Money spent on day 28 never earns anything back, and produce still in the
    shed at the final bell is worth exactly zero. Getting these three dates
    right is worth more than any amount of extra production.
    """
    day = obs["day"]
    return {
        "investing": day <= policy.get("invest_until_day", 99),
        "planting": day <= policy.get("plant_until_day", 99),
        "liquidating": day >= policy.get("liquidate_from_day", 99),
    }


# --- Job collection ---


def _collect_jobs(obs, policy, me, priv):
    """Every action worth taking this turn, most urgent first.

    A job is ``{"pos": (x, y), "op": [...], "need": (item, qty) | None}``.
    ``need`` means the acting unit must be carrying that item.
    """
    day = obs["day"]
    tiles = me["tiles"]
    seeds = priv["seeds"]
    shed = priv["shed"]

    feed, water, harvest, care, place, plant, build, fert, collect, dig = ([] for _ in range(10))

    animal_count = 0
    structures_free = {"COOP": [], "PASTURE": []}
    structures_total = {"COOP": 0, "PASTURE": 0}

    for y in range(BOARD):
        for x in range(BOARD):
            tile = tiles[y][x]
            if not isinstance(tile, dict):
                continue
            kind = tile.get("kind")
            pos = (x, y)

            if kind == "WEED":
                dig.append({"pos": pos, "op": ["DIG"], "need": None})
                continue

            if kind == "PLANT":
                if not tile["watered_today"]:
                    water.append({"pos": pos, "op": ["WATER"], "need": None})
                if _ready_to_harvest(tile, day, policy):
                    harvest.append({"pos": pos, "op": ["HARVEST"], "need": None})
                if policy.get("fertilize_crops") and tile["crop"] in policy["fertilize_crops"]:
                    info = CROPS[tile["crop"]]
                    window_start = (info["max_day"] + 1) // 2
                    age = day - tile["planted_day"]
                    if tile.get("fertilized_until_day", -1) < day and age >= window_start - 1:
                        fert.append({"pos": pos, "op": ["FERTILIZE"], "need": ("FERTILIZER", 1)})
                continue

            if kind in ("COOP", "PASTURE"):
                structures_total[kind] += 1
                if "animal" not in tile:
                    structures_free[kind].append(pos)
                    continue
                animal_count += 1
                a = ANIMALS[tile["animal"]]
                if not tile["fed_today"]:
                    feed.append({"pos": pos, "op": ["FEED"], "need": ("WHEAT", 1)})
                if tile.get("yield_units", 0) >= policy.get("animal_harvest_at", 1):
                    harvest.append({"pos": pos, "op": ["HARVEST"], "need": None})
                if policy.get("care") and not tile["cared_today"]:
                    care.append({"pos": pos, "op": ["CARE"], "need": None})
                if policy.get("collect_fertilizer") and tile.get("fertilizer_available"):
                    collect.append({"pos": pos, "op": ["COLLECT_FERTILIZER"], "need": None})

    n_units = 1 + len(me["hands"])
    invs = priv["inventories"]

    def carried(item):
        return sum(inv.get(item, 0) for inv in invs)

    shed_pos = _shed_tile(tiles)

    def restock(item, shortfall, per_trip):
        """Jobs that walk a unit to the shed and load `item`.

        These have to be real jobs rather than something idle units do, because
        when there is more field work than units nobody is ever idle -- which is
        exactly how a flock starves next to a full shed.
        """
        out = []
        available = shed.get(item, 0)
        if shortfall <= 0 or available <= 0:
            return out
        qty = max(1, min(per_trip, available))
        # Spread the load over several carriers rather than sending one hand to
        # visit every animal: a single unit with a full sack cannot walk a whole
        # quadrant inside 24 turns, so part of the herd goes unfed and its yield
        # bonus is lost. Cap at half the crew so watering still gets done.
        if policy.get("batched_restock"):
            trips = min(max(1, n_units // 2), max(1, (shortfall + qty - 1) // qty))
        else:
            trips = min(max(1, n_units // 2), shortfall)
        for _ in range(trips):
            # `skip_if_has` keeps a loaded hand from being sent back to the shed
            # instead of delivering what it is already carrying.
            out.append(
                {"pos": shed_pos, "op": ["PICKUP", item, qty], "need": None, "skip_if_has": item}
            )
        return out

    # Wheat for feeding is the one supply chain that kills assets when it breaks.
    restock_feed = restock("WHEAT", len(feed) - carried("WHEAT"), policy.get("carry", 6))

    # Place bought animals onto their empty structures.
    restock_animals = []
    for animal in policy.get("animals", []):
        kind = ANIMALS[animal]["structure"]
        in_hand = carried(animal)
        slots = len(structures_free[kind])
        for pos in structures_free[kind][: min(slots, in_hand + shed.get(animal, 0))]:
            place.append({"pos": pos, "op": ["PLACE", animal], "need": (animal, 1)})
        restock_animals += restock(animal, min(slots, shed.get(animal, 0)) - in_hand, 4)

    if fert:
        restock_animals += restock("FERTILIZER", len(fert) - carried("FERTILIZER"), 4)

    # Plant seeds we already own, and build structures on land we are not using.
    empties = _open_tiles(tiles)
    reserved = 0
    unlocked = sum(1 for row in tiles for t in row if t != "LOCKED")
    for plan in _build_plans(policy, day):
        kind = plan["kind"]
        target = plan.get("target", 0)
        if "share" in plan:
            # Never pave over every tile: an animal eats a wheat unit a day, and
            # that wheat has to be grown somewhere.
            target = min(target, int(unlocked * plan["share"]))
        room = max(0, target - structures_total[kind])
        for pos in empties[reserved : reserved + room]:
            build.append({"pos": pos, "op": ["BUILD_" + kind], "need": None})
        reserved += room

    if _season_phase(policy, obs)["planting"]:
        for crop in policy.get("crops", []):
            # Melon needs 10 days to first yield, wheat only 2, so they stop
            # being worth planting on very different days.
            if day > policy.get("plant_until", {}).get(crop, 99):
                continue
            have = seeds.get(crop, 0)
            if have <= 0:
                continue
            for pos in empties[reserved : reserved + have]:
                plant.append({"pos": pos, "op": ["PLANT", crop], "need": None})
            reserved += have

    # Urgency order. Feeding and watering come first because missing two days
    # in a row destroys the asset outright; the restock trips that make feeding
    # and placing possible sit directly in front of the work they enable.
    jobs = (
        restock_feed
        + feed
        + water
        + harvest
        + restock_animals
        + place
        + care
        + build
        + plant
        + fert
        + collect
        + dig
    )
    return jobs, animal_count


# --- Market planning ---


def _plan_market(obs, policy, me, priv, animal_count):
    day, hour = obs["day"], obs["hour"]
    money = me["money"]
    shed, seeds = priv["shed"], priv["seeds"]
    prices = obs["market"]["prices"]
    tiles = me["tiles"]
    phase = _season_phase(policy, obs)
    orders = []

    # Count animals waiting in the shed too. They eat as soon as they are placed,
    # so budgeting against placed animals alone buys a flock you cannot feed.
    flock = animal_count + sum(shed.get(a, 0) for a in policy.get("animals", []))

    # Wheat a hand is carrying to the coops is still wheat we own. Forgetting it
    # makes the farm sell its feed each morning and buy it back at twice the
    # price the same afternoon.
    carried_wheat = sum(inv.get("WHEAT", 0) for inv in priv["inventories"])

    def spend(cost):
        nonlocal money
        if money >= cost:
            money -= cost
            return True
        return False

    # 0. Sell first, and bank the proceeds into this turn's budget.
    #
    #    The engine walks the market queue in list order, so a SELL placed ahead
    #    of a BUY funds that buy on the same turn. Planning buys against the
    #    pre-sale balance instead is how a farm ends up permanently broke: every
    #    coin is committed before the day's produce has been turned into cash.
    sells = _plan_sells(obs, policy, priv, animal_count, phase)
    for order in sells:
        # Discount the quote: selling n units walks the price down as it fills.
        money += 0.8 * prices.get(order[1], 0) * order[2]
    orders += sells

    # 1. Hire. Cheap and the single highest-leverage order in the game -- but the
    #    fib pricing means a full crew is ~143/day, which is real money on day 1
    #    and rounding error on day 20. `hands_by_day` ramps the crew with the work.
    target_hands = policy.get("hands", 0)
    for from_day, count in policy.get("hands_by_day", []):
        if day >= from_day:
            target_hands = count
    if target_hands and hour <= 2:
        todo = min(target_hands - me["hires_today"], 5)
        for _ in range(max(0, todo)):
            orders.append(["HIRE"])

    # 2. Feed, before any expansion. An unfed animal dies permanently after two
    #    days, so topping up wheat outranks buying land or more livestock --
    #    getting this order wrong wipes out a whole flock on day 4.
    prefeed = policy.get("prefeed_stock", 0)
    if flock or prefeed:
        need = max(flock * policy.get("feed_days", 2), prefeed)
        gap = need - shed.get("WHEAT", 0) - carried_wheat
        wheat_price = prices.get("WHEAT", 25)
        if gap > 0 and wheat_price <= policy.get("max_wheat_price", 60):
            n = min(gap, policy.get("wheat_batch", 20))
            n = min(n, int(money // max(1, wheat_price)))
            if n > 0 and spend(n * wheat_price):
                orders.append(["BUY_PRODUCT", "WHEAT", n])

    # 3. Land, once we can afford it without starving the rest of the plan.
    #    Empty land earns nothing, so a livestock policy has to stock what it
    #    already owns before paying 1k-4k for more of it.
    bought = len(me["unlocked_quadrants"]) - 1
    stocked = animal_count >= policy.get("land_after_animals", 0)
    if (
        phase["investing"]
        and stocked
        and bought < policy.get("land", 0)
        and bought < len(LAND_PRICES)
    ):
        price = LAND_PRICES[bought]
        if money >= price + policy.get("land_buffer", 0):
            if spend(price):
                orders.append(["BUY_LAND"])

    # 4. Animals, capped by the structures we have or plan to have.
    #    `animals_need_wheat` refuses to buy livestock until the feed supply chain
    #    is actually running. Buying a flock on day 1 and starving it on day 4 is
    #    the most expensive mistake available in this game.
    animals_open = (
        phase["investing"]
        and day >= policy.get("animals_from_day", 0)
        and shed.get("WHEAT", 0) + carried_wheat >= policy.get("animals_need_wheat", 0)
    )
    for animal in policy.get("animals", []) if animals_open else []:
        info = ANIMALS[animal]
        want = policy.get("animal_target", {}).get(animal, 0)
        owned = shed.get(animal, 0)
        for y in range(BOARD):
            for x in range(BOARD):
                tile = tiles[y][x]
                if isinstance(tile, dict) and tile.get("animal") == animal:
                    owned += 1
        gap = want - owned
        # Capital sequencing. Until the land plan is finished, livestock may only
        # be bought with money above the price of the next quadrant -- otherwise
        # the flock eats every coin and the farm never expands. The exception is
        # a starter flock (`animal_floor`), which has to come first because land
        # cannot be paid for without some revenue.
        buffer = policy.get("animal_buffer", 0)
        if bought < policy.get("land", 0) and owned >= policy.get("animal_floor", 0):
            if bought < len(LAND_PRICES):
                buffer += LAND_PRICES[bought]
        # A flock is only worth what you can feed. Hold back enough cash to buy
        # wheat for the whole herd -- including the animals about to be bought --
        # for `feed_float_days`, or the herd starves before it ever produces.
        float_days = policy.get("feed_float_days", 0)
        wheat_price = prices.get("WHEAT", 25)
        n = 0
        for candidate in range(min(gap, policy.get("animal_batch", 2)), 0, -1):
            feed_float = (flock + candidate) * wheat_price * float_days
            if money >= candidate * info["cost"] + buffer + feed_float:
                n = candidate
                break
        if n > 0 and spend(n * info["cost"]):
            orders.append(["BUY_ANIMAL", animal, n])

    # 4. Seeds to keep every free tile busy.
    free_land = len(_open_tiles(tiles))
    if policy.get("max_plants") is not None:
        existing_plants = sum(
            1
            for row in tiles
            for tile in row
            if isinstance(tile, dict) and tile.get("kind") == "PLANT"
        )
        free_land = min(free_land, max(0, int(policy["max_plants"]) - existing_plants))
    for crop in policy.get("crops", []) if phase["planting"] else []:
        if day > policy.get("plant_until", {}).get(crop, 99):
            continue
        info = CROPS[crop]
        have = seeds.get(crop, 0)
        share = policy.get("crop_share", {}).get(crop, 1.0)
        # Never hold more unplanted seed than we can put in the ground shortly.
        # Buying 25 melon seeds at 80 each locks up 2,000 coins in inventory that
        # earns nothing until planted -- and is the difference between a farm that
        # compounds and one that goes broke on day 3.
        want = min(int(free_land * share), policy.get("seed_stock", 8))
        gap = min(want - have, policy.get("seed_batch", 8))
        if gap > 0 and money >= info["seed"] * gap + policy.get("seed_buffer", 0):
            if spend(info["seed"] * gap):
                orders.append(["BUY_SEED", crop, gap])

    # 6. Fertilizer, only if the policy actually applies it.
    if policy.get("fertilize_crops") and shed.get("FERTILIZER", 0) < policy.get("fert_stock", 0):
        n = policy["fert_stock"] - shed.get("FERTILIZER", 0)
        if money >= prices.get("FERTILIZER", 100) * n + policy.get("seed_buffer", 0):
            if spend(prices.get("FERTILIZER", 100) * n):
                orders.append(["BUY_PRODUCT", "FERTILIZER", n])

    return orders[: policy.get("max_orders", 10)]


def _plan_sells(obs, policy, priv, animal_count, phase):
    """Sell orders for this turn.

    The shed holds 100 items and silently discards the overflow, so pressure to
    sell rises as it fills -- and price floors are abandoned entirely once the
    season is closing, because unsold stock scores nothing.
    """
    day = obs["day"]
    shed = priv["shed"]
    prices = obs["market"]["prices"]

    used = sum(v for k, v in shed.items() if k in PRODUCTS)
    pressure = used >= policy.get("shed_pressure", SHED_CAP) or phase["liquidating"]
    # On the last day there is no tomorrow to feed, so the feed reserve is
    # just unsold stock. Wheat already in a hand's inventory counts toward the
    # reserve, so we do not hold back the same feed twice.
    flock = animal_count + sum(shed.get(a, 0) for a in policy.get("animals", []))
    carried_wheat = sum(inv.get("WHEAT", 0) for inv in priv["inventories"])
    if day >= policy.get("final_day", 29):
        reserve_wheat = 0
    else:
        reserve_wheat = max(
            policy.get("prefeed_stock", 0),
            max(0, flock * policy.get("feed_days", 2) - carried_wheat),
        )
    floors = policy.get("price_floor", {})
    chunk = policy.get("sell_chunk", 99)

    out = []
    for item in policy.get("sell_order", PRODUCTS):
        if len(out) >= policy.get("max_sell_orders", 4):
            break
        have = shed.get(item, 0)
        if item == "WHEAT":
            have -= reserve_wheat
        if have <= 0:
            continue
        if not pressure and prices.get(item, 0) < floors.get(item, 0):
            continue
        n = min(have, chunk)
        if n > 0:
            out.append(["SELL", item, n])
    return out


# --- Unit scheduling ---


def _assign(obs, policy, me, priv, jobs, animal_count):
    tiles = me["tiles"]
    positions = [tuple(me["farmer"])] + [tuple(p) for p in me["hands"]]
    invs = priv["inventories"]
    n = len(positions)
    ops = [["PASS"] for _ in range(n)]
    busy = [False] * n
    seat = int(obs.get("player", 0) or 0)
    if obs.get("hour", 0) == 0:
        _ROUTE_MEMORY[seat] = {}
    memory = _ROUTE_MEMORY.setdefault(seat, {})

    def inv_of(i):
        return invs[i] if i < len(invs) else {}

    def signature(job):
        return (tuple(job["pos"]), tuple(job["op"]), tuple(job["need"]) if job["need"] else None)

    # Optional logistics relay: loaded workers bank produce during the day instead
    # of carrying it until the engine's overnight reset. This makes sale proceeds
    # available for same-day investment and prevents harvested items from blocking
    # useful carrier inventory. Wheat is excluded because it is operational feed.
    drop_threshold = policy.get("drop_threshold", 0)
    if drop_threshold and obs.get("hour", 0) >= policy.get("drop_after_hour", 12):
        sx, sy = _shed_tile(tiles)
        for i in range(n):
            load = sum(inv_of(i).get(item, 0) for item in PRODUCTS if item != "WHEAT")
            if load < drop_threshold:
                continue
            busy[i] = True
            ops[i] = ["DROP"] if positions[i] == (sx, sy) else _step_toward(positions[i], (sx, sy))
            memory.pop(i, None)

    work_jobs = list(jobs)
    if policy.get("persistent_routing"):
        urgent = any(job["op"][0] in ("FEED", "PICKUP") for job in work_jobs)
        for i in range(n):
            if busy[i] or i not in memory:
                continue
            wanted = memory[i]
            match = None
            for index, job in enumerate(work_jobs):
                if signature(job) != wanted:
                    continue
                if urgent and job["op"][0] not in ("FEED", "PICKUP"):
                    continue
                need = job["need"]
                skip = job.get("skip_if_has")
                if need and inv_of(i).get(need[0], 0) < need[1]:
                    continue
                if skip and inv_of(i).get(skip, 0) > 0:
                    continue
                match = (index, job)
                break
            if match is None:
                memory.pop(i, None)
                continue
            index, job = match
            del work_jobs[index]
            d = _dist(positions[i], job["pos"])
            busy[i] = True
            ops[i] = job["op"] if d == 0 else _step_toward(positions[i], job["pos"])
            if d == 0:
                memory.pop(i, None)

    unserved = []
    for job in work_jobs:
        need = job["need"]
        best = None
        skip = job.get("skip_if_has")
        for i in range(n):
            if busy[i]:
                continue
            if need and inv_of(i).get(need[0], 0) < need[1]:
                continue
            if skip and inv_of(i).get(skip, 0) > 0:
                continue
            d = _dist(positions[i], job["pos"])
            # Soft zone ownership reduces long cross-quadrant trips while still
            # allowing urgent jobs to borrow a worker when no local one is free.
            if policy.get("cross_zone_penalty", 0):
                if _quadrant(*positions[i]) != _quadrant(*job["pos"]):
                    d += policy["cross_zone_penalty"]
            if best is None or d < best[0]:
                best = (d, i)
        if best is None:
            unserved.append(job)
            continue
        d, i = best
        busy[i] = True
        ops[i] = job["op"] if d == 0 else _step_toward(positions[i], job["pos"])
        if policy.get("persistent_routing"):
            if d == 0:
                memory.pop(i, None)
            else:
                memory[i] = signature(job)

    # Idle units restock whatever the unserved jobs were missing, so the next
    # turn has carriers ready. Without this, animals starve with a full shed.
    shed = priv["shed"]
    wants = []
    for job in unserved:
        if job["need"]:
            wants.append(job["need"][0])
    sx, sy = _shed_tile(tiles)
    for i in range(n):
        if busy[i]:
            continue
        pickup = None
        for item in wants:
            if shed.get(item, 0) > 0:
                pickup = item
                break
        if pickup is None and animal_count and shed.get("WHEAT", 0) > 0:
            carried = sum(inv_of(j).get("WHEAT", 0) for j in range(n))
            if carried < animal_count:
                pickup = "WHEAT"
        if pickup is None:
            continue
        if positions[i] == (sx, sy):
            qty = policy.get("carry", 6) if pickup == "WHEAT" else 1
            ops[i] = ["PICKUP", pickup, min(qty, shed.get(pickup, 0))]
            wants = [w for w in wants if w != pickup]
        else:
            ops[i] = _step_toward(positions[i], (sx, sy))
        busy[i] = True

    if policy.get("persistent_routing"):
        for i in range(n):
            if not busy[i]:
                memory.pop(i, None)

    return ops


# --- Entry point ---


def act(obs, policy):
    me = obs["farms"][obs["player"]]
    priv = obs["private"]
    jobs, animal_count = _collect_jobs(obs, policy, me, priv)
    market = _plan_market(obs, policy, me, priv, animal_count)
    ops = _assign(obs, policy, me, priv, jobs, animal_count)
    return {"farmer": ops[0], "hands": ops[1:], "market": market}


def agent(obs):
    """Kaggriculture entry point: one observation in, one action dict out."""
    return act(obs, POLICY)
